### ISSUE TITLE
Missing Requirement.txt file

### ISSUE THREAD

**Issue by hacker-saran** [QianWangX/VidSeg_diffusion#1]
I noticed that the requirements.txt file is missing from the repository. This file is essential for setting up the project environment as it specifies all the necessary dependencies.

Could you please add the requirements.txt file to the repository? This will ensure that all contributors can easily install the required packages and maintain a consistent development environment.

**Comment by QianWangX** [comment]
@hacker-saran Great, thank you for pointing out the missing file!
