### ISSUE TITLE
svd.yaml config file has user private path referenced

### ISSUE THREAD

**Issue by BioBerl** [QianWangX/VidSeg_diffusion#4]
In VidSeg_diffusion/configs/inference/svd.yaml the checkpoints file path refers to the op's ckpt_path: /home/wangq0e/research/generative-models/checkpoints/svd.safetensors instead of a general checkpoint file path.

**Comment by QianWangX** [comment]
Hi @BioBerl , thank you for mentioning this. Feel free to modify the path with your local path for the SVD checkpoint :)
